<a href="https://colab.research.google.com/github/MONSERRATMB33/unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy es una libreria de python.
NumPy se utiliza para trabajar matrices o arreglos
NumPy es la abreviatura de "python numerico"
Tambien tiene funciones para trabajar en el dominio de algebra lineal,la transformada y las matrices
en python tenemos listas que sirven como matrices,pero son lentas de procesar.NumPy tiene como objetivo proporcionar en objeto de matriz que sea 50 veces mas rapido que las listas tradicionales

In [1]:
#Primero tenemos que importar la libreria
import numpy

arreglo = numpy.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


Numpy como np
NumPY generalmete de importa bajo el alias np.en python los alias son un nombre alternativo para referirse a la misma cosa

In [2]:
import numpy as np

arreglo = np.array([6,7,8,9,10])
print(arreglo)

[ 6  7  8  9 10]


comprobando la version de NumPy la cadena de version se almacena en el atributo_version_

In [4]:
import numpy as np
print (np._version_)

AttributeError: module 'numpy' has no attribute '_version_'

NumPy crea matrices
Crea un objeto ndarray de NumPy
NumPy se utiliza para trabajar con matrices.
el objeto de matriz se llama ndarray.
podemos crear un NumPy ndarray utilizando la funcion array()

In [5]:
import numpy as np

arreglo = np.array(["Raul","David","Leonel","Monserrat"])
print (arreglo)
print (type(arreglo))

['Raul' 'David' 'Leonel' 'Monserrat']
<class 'numpy.ndarray'>


Dimensiones en matrices
Una dimension en matrices es un nivel
de profundidad de matriz (matrices unidas)
Una matriz unida contiene matrices como elementos
Matrices 0-D.son elementos de una matriz.
cada valor de una matrizes una matriz 0-D.Ejemplo:crea una matriz 0-D con valor de 42

In [6]:
import numpy as np

arreglo = np.array(42)

print (arreglo)

42


Matrices 1-D
Una matriz que tiene matrices 0-D como elementos se denomina
matriz unidimensional o 1-D. Estas son las matrices mas comunes y basicas.
Ejemplo:Crea una matriz de 1-D que tenga los valores 1,2,3,4,5

In [7]:
import numpy as np

arreglo = np.array([1,2,3,4,5])

print (arreglo)

[1 2 3 4 5]


Matrices 2D
una matriz que tiene matrices 1-D como elementos
se denomina matriz 2-D. A menudo se utilizan para
representar matrices de segundo orden.NumPy tiene
un submodulo completo dedicado a operaciones con
matrices llamado numpy.mat
Ejemplo:Crea una matriz 2D que contenga dos matrices con los valores 1,2,3 y 4,5,6

In [8]:
import numpy as np

arreglo = np.array([[1,2,3,],[4,5,6]])

print (arreglo)

[[1 2 3]
 [4 5 6]]


Matrices 3D
Una matriz que tiene matrices 2D se denomina matriz 3D.
estas matrices se utilizan para representar una matriz de tener orden.
Ejemplo:Crea una matriz 3D con 2 matrices bidimensionales,ambas conteniendo
dos matrices con los valores 1,2,3 y 4,5,6

In [9]:
import numpy as np

arreglo = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print (arreglo)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
